# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbd0692eafd4f090b478a381fb4286ffe7c225964da482ba4148639cee9977325f019c207555d029a5842489e9fd816db63c3df770c201d4339629d6760c791b

test:
  secret_key_base: e5f1d92e8c42d56554564de7913735da95c6cacd2873c37d3d51f22ed9e4a073ba0847df3810cc1d52e37bfc22a8583831aab34086e327b04f050ac1851bba6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
